name: month_year_picker
description: The month year picker inspired by the Flutter's date picker design.
version: 0.2.2+4
homepage: https://github.com/zulfahmi93/month-year-picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '3.32.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 

dev_dependencies:
  flutter_lints: ^6.0.0
